### ISSUE TITLE
Where to rectify image?

### ISSUE THREAD

**Issue by klepo** [5G-ERA/CollisionAvoidanceService#19]

**Comment by klepo** [comment]
On the client side and/or also on the NetApp side?

**Comment by RomanJuranek** [comment]
* On the client side - this means that we need to transcode the video stream - rectify->encode->send
  * Higher computational demands in robot, lower data rate through net
* On the NetApp side - we can re-send the data directly if it is rtsp stream. On the other hand if we read raw data from camera (which is probable), we need to transcode anyway.
  * Maybe lower computational demands (in case of re-sending the stream), high data rate.

I am in favour of rectification on client side/
